version: '3.3'
services:
    all-in-one:
        container_name: nextcloud-aio-mastercontainer
        restart: always
        ports:
            - '80:80'
            - '8443:8443'
            - '8080:8080'
            - '443:443'
        volumes:
            - 'nextcloud_aio_mastercontainer:/mnt/docker-aio-config'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        environment:
            - NEXTCLOUD_UPLOAD_LIMIT=1000G
            - NEXTCLOUD_DATADIR=nextcloud_aio_nextcloud_datadir
            - NEXTCLOUD_MAX_TIME=3600000000
            - SKIP_DOMAIN_VALIDATION=true
        image: 'nextcloud/all-in-one:latest'