services:
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
      file: hwaccel.ml.yml
      service: cuda
    volumes:
      - model-cache:/cache
    restart: always
    ports:
      - 3003:3003
    labels:
      - 'docktail.service.enable=true'
      - 'docktail.service.name=ajh-desktop-immich-remote-ml'
      - 'docktail.service.port=3003'

volumes:
  model-cache:
