FROM arm64v8/ubuntu:22.04

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

RUN apt update
RUN apt install samba krb5-user krb5-config winbind libpam-winbind libnss-winbind smbclient
