[libdefaults]
    default_realm = YOUR_REALM.COM
    dns_lookup_realm = false
    dns_lookup_kdc = false
 
[realms]
    YOUR_REALM.COM = {
        kdc = your_server_ip
        admin_server = your_server_ip
    }
 
[domain_realm]
    .your_domain.com = YOUR_REALM.COM
    your_domain.com = YOUR_REALM.COM
