#Host:Container
version: '3.3'
services:
    dashy:
        ports:
            - '4000:80'
        volumes:
            - '/clouddata/Dashy/dashy-conf.yml:/app/public/conf.yml'
        container_name: my-dashboard
        restart: always
        image: 'lissy93/dashy:latest'
